export const lightTheme = {
  background: "#FAFAFA",
  surface: "#F8F9FA",
  text: "#1A1A1A",
  secondaryText: "#555555",
  primary: "#7CACF8",
  accent: "#4AA9E2",
  border: "#E0E0E0",
  card: "#FFFFFF",
  modalBackground: "#FFFFFF",
  noColorBackground: "#ECECEC",
  disabled: "#E0E0E0",
  disabledText: "#9CA3AF",
  editButton: "#FFFFFF",
  black: "#000000",
};
